### ISSUE TITLE
multiply function inner loop is the same for each element of the result matrix

### ISSUE THREAD

**Issue by xoich** [webDva/matrixmul#2]
Multiplying [2 1 / 0 3] * [1 0 / 1 2] returns [8 8 / 8 8] instead of the expected [3 2 / 3 6]

**Comment by webDva** [comment]
First of all, thank you for your support by bringing this issue to my attention.

Commit c342be11e0929f7b61bbb38ab5379d84933419f7 should fix this issue.

However, I'm not certain as I don't have a simple and effective means for doing thorough tests, which is why this issue existed in the first place. I am now more inclined to expending more effort and energy to finding such a means.

Still, I will close this issue in twenty-four hours as it's likely that the aforementioned commit does in fact fix this issue.
